name: cyber-lab-lite

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-lite
    restart: unless-stopped
    ports:
      - "80:80"
      - "8443:8443"
    environment:
      - ACME_EMAIL=${ACME_EMAIL}
      - GOPHISH_ADMIN_DOMAIN=${GOPHISH_ADMIN_DOMAIN}
      - GOPHISH_LANDING_DOMAIN=${GOPHISH_LANDING_DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - gophish
    networks:
      - default
      - phish-net

  gophish:
    image: gophish/gophish:latest
    container_name: gophish-lite
    restart: unless-stopped
    networks:
      phish-net:
        ipv4_address: 172.30.0.10
    volumes:
      - gophish_data:/opt/gophish

  postfix:
    image: mwader/postfix-relay:latest
    container_name: postfix-relay-lite
    restart: unless-stopped
    environment:
      - POSTFIX_myhostname=simulasyon.local
      - POSTFIX_mynetworks=127.0.0.0/8,172.30.0.10/32
      - POSTFIX_relayhost=[159.253.46.182]:587
      - POSTFIX_smtpd_recipient_restrictions=permit_mynetworks,reject
    networks:
      phish-net:
        ipv4_address: 172.30.0.20

networks:
  phish-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  gophish_data:
  caddy_data:
  caddy_config:
